
cc_library(
    name = "serializer_lib",
    srcs = glob(["*.cc"], allow_empty=True),
    hdrs = glob(["*.h"], allow_empty=True),
    visibility = ["//visibility:public"],  # needed for subpackages
)
