
cc_binary(
    name = "serdel",
    srcs = ["main.cc"],
    deps = [
        "//serdel/msg/base:msg_base_lib",  # 
       "//serdel/msg/a:a_msg_lib",  # 
              "//serdel/msg/b:b_msg_lib",  # 

    ],
)