cc_test(
    name = "cord_test",
    size = "small",
    srcs = ["cord_test.cc"],
    deps = [
        "//cord/inc:libcord",#the cord is name of FOLDER!
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)