filegroup(
    name = "run_benchmark_sh",
    srcs = ["run_benchmark.sh"],
    visibility = ["//bench:__pkg__"], #the bench is name of FOLDER!

)

filegroup(
    name = "draw_py",
    srcs = ["draw.py"],
    visibility = ["//bench:__pkg__"], #the bench is name of FOLDER!

)
filegroup(
    name = "run_perf_sh",
    srcs = ["run_perf.sh"],
    visibility = ["//bench:__pkg__"], #the bench is name of FOLDER!

)